# Generated by Django 4.1.2 on 2022-11-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfamiliar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
